# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'TicText' do
  pod 'Parse'
  pod 'ParseFacebookUtils'
  pod 'ParseCrashReporting'
  pod 'Facebook-iOS-SDK'
  pod 'MBProgressHUD'
  pod 'JSQMessagesViewController'
  pod 'JMStaticContentTableViewController'
end

target 'TicTextTests' do
  pod 'Parse'
  pod 'ParseFacebookUtils'
  pod 'ParseCrashReporting'
  pod 'Facebook-iOS-SDK'
  pod 'MBProgressHUD'
  pod 'OCMock', '~> 3.1'
end

